global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'Agent'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['agent:443']
  - job_name: 'BaseEnricher'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['baseenricher:443']