version: '3.4'

services:
  baseenricher:
    image: ${DOCKER_REGISTRY-}baseenricher
    build:
      context: .
      dockerfile: BaseEnricher/Dockerfile
    environment:
      - InBrokerHostname=rabbitmq.allinone.local
      - InBrokerTopic=base_message_queue
      - OutBrokerHostname=rabbitmq.allinone.local
      - OutBrokerTopi=enriched_message_queue
    depends_on:
      - "rabbitmq.allinone.local"

  rabbitmq.allinone.local:
    container_name: "rabbitmq.allinone.local"
    hostname: "rabbitmq.allinone.local"
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'