version: '3.4'

services:
  baseenricher:
    image: ${DOCKER_REGISTRY-}baseenricher
    build:
      context: .
      dockerfile: BaseEnricher/Dockerfile
    environment:
      - InBrokerHostname=rabbitmq.allinone.local
      - InBrokerPort=5672
      - InBrokerTopic=base_message_queue
      - OutBrokerHostname=rabbitmq.allinone.local
      - OutBrokerPort=5672
      - OutBrokerTopic=enriched_message_queue
    depends_on:
      - "rabbitmq.allinone.local"
    networks:
     - logingestor-net


  rabbitmq.allinone.local:
    container_name: "rabbitmq.allinone.local"
    hostname: "rabbitmq.allinone.local"
    image: rabbitmq:3.11-management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    networks:
     - logingestor-net

  fswriter:
    image: ${DOCKER_REGISTRY-}fswriter
    build:
      context: .
      dockerfile: FSWriter/Dockerfile
    depends_on:
      - "rabbitmq.allinone.local"
    networks:
     - logingestor-net
    volumes:
     - filesystem-storage:/usr/share/log-ingestor/data
    environment:
     - InBrokerHostname=rabbitmq.allinone.local
     - InBrokerPort=5672
     - InBrokerTopic=enriched_message_queue
     - StoragePathInContainer=/usr/share/log-ingestor/data

  agent:
    image: ${DOCKER_REGISTRY-}agent
    build:
      context: .
      dockerfile: Agent/Dockerfile
    networks:
     - logingestor-net


volumes:
  filesystem-storage:

networks:
  logingestor-net:


