name: fs-writer

on:
  push:
    branches: [ main ]
    paths:
    - 'src/LogIngestor/FSWriter.UnitTests/**'
    - 'src/LogIngestor/FSWriter/**'
    - '.github/workflows/**'

  pull_request:
    branches: [ main ]
    paths:
    - 'src/LogIngestor/FSWriter.UnitTests/**'
    - 'src/LogIngestor/FSWriter/**'
    - '.github/workflows/**'
env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore src/LogIngestor/FSWriter.UnitTests/
      
    - name: Build
      run: dotnet build src/LogIngestor/FSWriter.UnitTests/ --configuration Release --no-restore
    
    - name: Test
      run: dotnet test src/LogIngestor/FSWriter.UnitTests/ --no-restore --verbosity normal
